---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utimbox
  namespace: utimbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: utimbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: utimbox
    namespace: utimbox

