---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uubox
  name: uubox
  namespace: uubox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uubox
  template:
    metadata:
      labels:
        app: uubox
    spec:
      containers:
      - image: quay.io/mamafun/uubox:latest
        imagePullPolicy: IfNotPresent
        name: uubox
      serviceAccount: uubox
      serviceAccountName: uubox

